name: Build and Deploy CV

on:
  push:
    branches:
      - master  # Make sure this matches your branch

jobs:
  build:
    runs-on: ubuntu-24.04  # Use the correct Ubuntu version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: ls -alh

    - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-extra

    - name: Navigate to latex folder and compile CV
      run: |
        cd latex  # Go into the LaTeX folder
        pdflatex cv.tex  # Compile LaTeX file to PDF

    - name: Move PDF to root folder
      run: |
        mv latex/cv.pdf ./cv.pdf  # Move the generated PDF to the root folder

    - name: Commit and push PDF to GitHub
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"
        git add cv.pdf  # Add the PDF to the staging area
        git commit -m "Add generated CV PDF"  # Commit the file
        git push origin master  # Push to your repository (replace master with your branch name if necessary)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token to commit changes

