name: Build and Deploy CV

on:
  push:
    branches:
      - master  # Make sure the branch name matches your current branch

jobs:
  build:
    runs-on: ubuntu-24.04  # Updated runner version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-latex-base texlive-latex-extra

    - name: Compile CV
      run: pdflatex cv.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: ./cv.pdf
