name: Build and Deploy CV

on:
  push:
    branches:
      - master  # Make sure the branch name matches your current branch

jobs:
  build:
    runs-on: ubuntu-24.04  # Use ubuntu-24.04 instead of ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: ls -alh

    - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-extra

    - name: Navigate to latex folder and compile CV
      run: |
        cd latex  # Navigate to the folder where cv.tex and education.tex are located
        pdflatex cv.tex  # Compile cv.tex from within the latex folder

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: ./latex/cv.pdf  # Path to the generated PDF in the latex folder
